### ISSUE TITLE
make unable to fetch uClibc-ng-1.0.42

### ISSUE THREAD

**Issue by tayfun57** [pfichtner/pfichtner-freetz#1]
Hello together,

here is the complete console output:

** End of the configuration.
*** Execute 'make' to start the build or try 'make help'.

Freetz-NG 20213M-5bb89d0aa master 2022-09-09
---> toolchain/target/uclibc ... 
downloading ... tools/freetz_download dl uClibc-ng-1.0.42.tar.xz https://downloads.uclibc-ng.org/releases/1.0.42 ec6dae44ce86558885e56bc3bef6bd4d082397114e6e1fc15795f71e804d7016 

--2022-09-12 08:17:49--  https://downloads.uclibc-ng.org/releases/1.0.42/uClibc-ng-1.0.42.tar.xz
Resolving downloads.uclibc-ng.org (downloads.uclibc-ng.org)... 89.238.66.15, 2a00:1828:2000:679::23
Connecting to downloads.uclibc-ng.org (downloads.uclibc-ng.org)|89.238.66.15|:443... failed: No route to host.
Connecting to downloads.uclibc-ng.org (downloads.uclibc-ng.org)|2a00:1828:2000:679::23|:443... failed: Cannot assign requested address.
Retrying.

--2022-09-12 08:17:51--  (try: 2)  https://downloads.uclibc-ng.org/releases/1.0.42/uClibc-ng-1.0.42.tar.xz
Connecting to downloads.uclibc-ng.org (downloads.uclibc-ng.org)|89.238.66.15|:443... failed: No route to host.
Connecting to downloads.uclibc-ng.org (downloads.uclibc-ng.org)|2a00:1828:2000:679::23|:443... failed: Cannot assign requested address.
Retrying.

--2022-09-12 08:17:55--  (try: 3)  https://downloads.uclibc-ng.org/releases/1.0.42/uClibc-ng-1.0.42.tar.xz
Connecting to downloads.uclibc-ng.org (downloads.uclibc-ng.org)|89.238.66.15|:443... failed: Connection timed out.
Connecting to downloads.uclibc-ng.org (downloads.uclibc-ng.org)|2a00:1828:2000:679::23|:443... failed: Cannot assign requested address.
Giving up.

Download failed - "https://downloads.uclibc-ng.org/releases/1.0.42/uClibc-ng-1.0.42.tar.xz"  ->  error code 4

--2022-09-12 08:18:15--  https://freetz-ng.dropfiles.net/uClibc-ng-1.0.42.tar.xz
Resolving freetz-ng.dropfiles.net (freetz-ng.dropfiles.net)... 85.13.135.121
Connecting to freetz-ng.dropfiles.net (freetz-ng.dropfiles.net)|85.13.135.121|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-09-12 08:18:15 ERROR 404: Not Found.

Download failed - "https://freetz-ng.dropfiles.net/uClibc-ng-1.0.42.tar.xz"  ->  error code 8

--2022-09-12 08:18:15--  https://freetz.magenbrot.net/uClibc-ng-1.0.42.tar.xz
Resolving freetz.magenbrot.net (freetz.magenbrot.net)... 31.172.113.113
Connecting to freetz.magenbrot.net (freetz.magenbrot.net)|31.172.113.113|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-09-12 08:18:15 ERROR 404: Not Found.

Download failed - "https://freetz.magenbrot.net/uClibc-ng-1.0.42.tar.xz"  ->  error code 8

--2022-09-12 08:18:15--  https://freetz.wirsind.info/uClibc-ng-1.0.42.tar.xz
Resolving freetz.wirsind.info (freetz.wirsind.info)... 188.165.115.52
Connecting to freetz.wirsind.info (freetz.wirsind.info)|188.165.115.52|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-09-12 08:18:15 ERROR 404: Not Found.

Download failed - "https://freetz.wirsind.info/uClibc-ng-1.0.42.tar.xz"  ->  error code 8

--2022-09-12 08:18:15--  https://raw.githubusercontent.com/Freetz-NG/dl-mirror/master/uClibc-ng-1.0.42.tar.xz
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-09-12 08:18:16 ERROR 404: Not Found.

Download failed - "https://raw.githubusercontent.com/Freetz-NG/dl-mirror/master/uClibc-ng-1.0.42.tar.xz"  ->  error code 8
make[1]: *** [toolchain/make/target/uclibc/uclibc.mk:73: dl/uClibc-ng-1.0.42.tar.xz] Error 1
make: *** [Makefile:46: envira] Terminated

**Comment by pfichtner** [comment]
There's nothing wrong within the docker image. Please file the issue (or open a discussion) at [Freetz-NG](https://github.com/Freetz-NG/freetz-ng/)

**Comment by pfichtner** [comment]
@tayfun57 Please try again since it seems that downloads.uclibc-ng.org was down while you tried it, so your problem should be gone. Please comment if so or not.

**Comment by tayfun57** [comment]
Hey @pfichtner i was able to build. Thank you.
